CREATE DATABASE test;

use test;

CREATE TABLE users (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age INT(3) NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP);
